name: RL_PROJECT
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - jupyter
  - ipykernel
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - scipy>=1.10
  - tqdm>=4.65
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - gymnasium[mujoco]>=1.0.0
    - stable-baselines3>=2.3.0
    - sb3-contrib>=2.3.0
    - torch>=2.0.0
    - tensorboard>=2.14.0
    - rliable>=1.1.0
    - statsmodels>=0.14.0
